version: '3.7'

networks:
   consul-network:
     name: consul-network


services:


  gateway:
    #    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    #    image: moonbse/backend:latest
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./src/main/resources/nginx.conf:/app/nginx.conf
    networks:
      - consul-network
    ports:
      - "80:8080"


  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./src/main/resources/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - consul-network


  
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    networks:
      - consul-network
    volumes:
      - ./server.json:/consul/config/server.json:ro
    ports:
      - "8505:8505"
#      - "8600:8600/tcp"
#      - "8600:8600/udp"

#
  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    depends_on:
      - consul-server
    
   
    command: "consul://consul-server:8505"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - consul-network

